variable "db_subnet_group_name" {}
variable "private_subnets" {}
variable "allocated_storage" {}
variable "engine" {}
variable "engine_version" {}
variable "identifier" {}
variable "instance_class" {}
variable "db_name" {}
variable "vpc_security_group_ids" {}
variable "username" {}
variable "password" {}